### ISSUE TITLE
neuprint_get_synapses() broken

### ISSUE THREAD

**Issue by hjmh** [natverse/neuprintr#10]
Full error message: 

<img width="947" alt="Screen Shot 2020-01-13 at 1 43 49 PM" src="https://user-images.githubusercontent.com/10639803/72282482-bd328900-360a-11ea-90b3-7d527ffa98bf.png">

**Comment by romainFr** [comment]
Will get fixed in #11

**Comment by hjmh** [comment]
Yes, this seems to be fixed.
