### ISSUE TITLE
Error in neuprint_ROI_mesh

### ISSUE THREAD

**Issue by IsabelDAlessandro** [natverse/neuprintr#143]
I'm encountering an error when using the `neuprint_ROI_mesh` function. 

Calling `neuprint_ROI_mesh(roi = "EB") ` gives the error `Error in sapply(x$shapes, function(y) unique(y$material_ids)) + 1L : 
  non-numeric argument to binary operator`

**Comment by jefferis** [comment]
Dear Isabel, there was a bug in readobj v0.4.0. Please upgrade to 0.4.1. 0.4.1 may already have been on CRAN when you last upgraded but it takes a few days for binary packages for Mac and windows to appear so you might need to install with type='source' (you will need a C compiler for this). Best wishes, Greg.

**Comment by IsabelDAlessandro** [comment]
That solved it. Thank you!
