### ISSUE TITLE
the "details" argument field in neuprint_connection_table doesn't work with character vector

### ISSUE THREAD

**Issue by artxz** [natverse/neuprintr#173]
seems it hasn't been implemented:

https://github.com/natverse/neuprintr/blob/1bf392fb896710d64e1b03cdddb38ea05a54f5d1/R/connectivity.R#L302

**Comment by jefferis** [comment]
Hi @artxz, thanks for the report. Could you give an example? That line of code is actually fine (if details is a character vector then `isTRUE(details)` is `FALSE` and program execution continues):
```
> isTRUE(c("a", "b"))
[1] FALSE
```
But that doesn't mean there isn't another bug ...

**Comment by artxz** [comment]
Hi @jefferis , I did an update and it seems to be working fine now. For the record, previously, 
`neuprint_connection_table(1807537598, details=c("name","type"))`
returns an error (sorry the linked line was incorrect):
```
Error in if (details) firstcols = c(firstcols, "name", "type") : 
  argument is not interpretable as logical
```

**Comment by jefferis** [comment]
ok great. the best bugs are the ones we already fixed! Thanks again for your input!
