### ISSUE TITLE
improve heal skeleton option

### ISSUE THREAD

**Issue by jefferis** [natverse/neuprintr#32]
@alexanderbates although I haven't checked in detail, the heal skeleton option looks a bit too simple to be doing the right thing. @SridharJagannathan has a new implementation that we should be able to use.

**Comment by jefferis** [comment]
See https://github.com/natverse/neuprintr/blob/bf672085176e27faa065fcf85dbf99552f4b89f2/R/neurons.R#L183-L198

**Comment by SridharJagannathan** [comment]
@alexanderbates It is available here: https://github.com/natverse/nat/blob/feature/elmr_features/R/neuron.R#L1107 and will be merged to master after review by @jefferis next week.

**Comment by SridharJagannathan** [comment]
Hmm, just attaching the figure with the latest implementation of `stitch_neurons_mst` where the pathological part is also connected (which needs to be fixed)
<img width="888" alt="Screenshot 2020-01-29 at 12 08 39" src="https://user-images.githubusercontent.com/13106358/73355596-5e1e7680-4290-11ea-9326-c46d081bf9fc.png">

**Comment by SridharJagannathan** [comment]
I have made a new implementation in `nat::stitch_neurons_mst` which has a parameter `thresh_el` that has the edge length threshold. Only edges below this threshold will be added (currently fixed at 1000 microns). See test below (the green is the current output, overlayed on top of blue previous ouput)
<img width="677" alt="Screenshot 2020-01-29 at 14 48 17" src="https://user-images.githubusercontent.com/13106358/73367389-66ce7700-42a7-11ea-96f1-096060b3e3f9.png">

**Comment by jefferis** [comment]
Just a note that we are getting close to having a fast/robust implementation of the new healing code in https://github.com/natverse/nat/pull/424. There was also a separate change in `as.seglist.igraph` that offers significant speed-ups.

**Comment by jefferis** [comment]
Closed by #76
