### ISSUE TITLE
`neuprint_read_neurons` fails because of `id2bit64`

### ISSUE THREAD

**Issue by romainFr** [natverse/neuprintr#41]
For example 
```r
test <- neuprint_search("PFL1.*")
neuprint_read_neurons(test$bodyid)
```

Returns 
```
Error in neuprint_read_neurons(test$bodyid) : 
  Error: none of the given bodyids have skeletons that could be fetched
```

`neuprint_read_neuron` on single bodyids works, as well as `neuprint_read_neurons` if I remove the call to `id2bit64` in the `nlapply` call.

**Comment by jefferis** [comment]
Yes I've fixed that same bug in a couple of places already. Let me finish. It's a stupid thing but `as.list` on a vector of bit64 objects turns them into 8 byte numeric values. It's basically safest to keep them as character vectors.

**Comment by romainFr** [comment]
Great, I was getting very confused by that

**Comment by jefferis** [comment]
We now have `id2char` as well. Pass your bodyids through that if you want to be sure that they are all good.
