### ISSUE TITLE
Option for neuprint_ROIs() to get only superLevelROIs

### ISSUE THREAD

**Issue by mmc46** [natverse/neuprintr#55]
It would be useful to have an option in `neuprint_ROIs()` to get either all or only the superLevelROIs, which are the standard ones.

```
rois = sort(neuprint_ROIs())
rois[grepl(names(rois), pattern = "superLevelROI")]
```

**Comment by alexanderbates** [comment]
Thank you! I have done this in 3ddec485cb241cfd610bd32e9f040caa60b72eeb
