### ISSUE TITLE
neuron semantics

### ISSUE THREAD

**Issue by istvantaisz** [natverse/neuprintr#58]
`neuprint_read_neuron` does not accept multiple bodyIDs and you need to use `neuprint_read_neurons` for that, but `neuprint_read_neuron_simple` does accept multiple bodyIDs and doesn't esixt with neurons. It works similarly with `catmaid_read_neuron/s` and I'm not sure what's the purpose of having both functions

**Comment by alexanderbates** [comment]
I have now hidden `neuprint_read_neuron` on the branch `new-heal`, so it will disappear when merged into `master`. @romainFr can we change `neuprint_read_neuron_simple` to `neuprint_read_neurons_simple` ? Just to avoid this sort of confusion?

**Comment by jefferis** [comment]
neuprint_read_neuron_simple is just neuprint_read_neurons without all the bells and whistles. It was originally intended to be internal. Maybe one could just make sure that neuprint_read_neurons can easily operate in a simple fashion without fetching extra bits.

**Comment by jefferis** [comment]
This is now resolved by the merge of #76
