### ISSUE TITLE
use neuprint_datasets() to define a default dataset

### ISSUE THREAD

**Issue by jefferis** [natverse/neuprintr#68]
Hard coded value of "hemibrain:v1.0" is already out of date

**Comment by jefferis** [comment]
See https://github.com/natverse/rcatmaid/blob/f92b3655124bc8327a4ad10a0d18bf1ef9ca2ce0/R/catmaid_connection.R#L509-L531 for a related implementation.

**Comment by mmc46** [comment]
We should check if the current specification matches an available dataset.
