### ISSUE TITLE
by.roi argument in neuprint_connection_table broken -- still returns broken down connections

### ISSUE THREAD

**Issue by markuspleijzier** [natverse/neuprintr#69]
Example:

mbon_df <- neuprint_connection_table(799586652, prepost = "POST", by.roi = FALSE)
mbon_df

**Comment by alexanderbates** [comment]
Hey Markus! Sorry not sure what's happening there. This line of code works for me... do you have an up-to-date install? What is returned? I get 941 (all unique) postsynaptic partners for this neuron and no `roi` field.

**Comment by jefferis** [comment]
Works for me as well. 
```
> mbon_df
       bodyid    partner prepost weight
1   799586652 5813022234       1    465
2   799586652 5901213440       1    312
3   799586652  667857582       1    257
4   799586652  424767514       1    197
```

Perhaps @alexanderbates is right that your install may be out of date.

**Comment by jefferis** [comment]
@markuspleijzier can you close if this works for you now? Note that I pushed a small fix to ensure that `by.roi` is always correctly handled when `progress=TRUE` (see #70) but that wouldn't have been relevant for the example code you gave in this issue.
