### ISSUE TITLE
fetching and plotting some bodyids fails in neuprintr

### ISSUE THREAD

**Issue by lisa-marin** [natverse/neuprintr#71]
```
pvl = c(419908058, 479935033)
# can't fetch skeletons for some reason
pvl.plot = neuprint_read_neurons(pvl)
plot3d(pvl.plot, lwd = 2, col = sample(lacroix,length(pvl),replace=TRUE))
```

This exact same code works for other bodyids, and the bodyids listed above can be plotted in Neuprint Explorer. But in neuprintr, I get the following error message:

Error in neuprint_read_neurons(pvl) : 
  Error: none of the given bodyids have skeletons that could be fetched

**Comment by jefferis** [comment]
Which version of neuprintr is Installed? We have been updating v fast. Need the github sha1 from the description field.

**Comment by lisa-marin** [comment]
I just installed the latest version of neuprintr but still get the error message.

**Comment by jefferis** [comment]
Yes, thanks, sorry, I see that too. I think this is a slightly fiddly issue with how some neurons are healed. We (mostly Sri / Alex) basically have a solution but there are some largish changes required under the hood that I need to approve. Depending on what you need to do next, you can do:
```
pvl.plot = neuprint_read_neurons(pvl, heal=FALSE)
```
as a work around. The neurons will be in multiple pieces, but that won't stop you from plotting them etc.

**Comment by jefferis** [comment]
Closing as related to #32
