### ISSUE TITLE
Add statusLabel to neuprint_get_meta

### ISSUE THREAD

**Issue by mmc46** [natverse/neuprintr#73]
There is a new field, `statusLabel` in the metadata - it shows in neuprint-python.

Can this be added to the output of `neuprint_get_meta()`?

We think the difference between `status` and `statusLabel` is due to the fact that just before the release many bodyids got the status 'Traced' even though their status at the time was not 'Traced'. So `status` reflects the value in the released dataset, whereas `statusLabel` corresponds to the previous one.

For example: bodyids 
```
c("2292327595", "2262328440", "2262332862", "2262324061", "2231289277",
"2200228798", "2231289424", "2230931053", "2231298154", "2262328549",
"2231298121", "2261992182", "2230931155", "2231289333", "2261637853",
"2321337738", "2320983805", "2292672665", "2200228767", "2230931077",
"5813046796", "2230926964", "2231293853", "2200228723", "2261987736",
"2320655662", "2231284881", "2261965878", "2261970553", "2231293819",
"2321001244", "2231289597", "2231289459", "2200569724", "2291999690",
"2290303228", "2262324036", "5813034811", "2231298170", "2231289545",
"5813005580")
```

have `status` == 'Traced' and `statusLabel` == 'Leaves'

**Comment by jefferis** [comment]
Do we have any more info than that? Seems rather vague thing to add to documentation.

**Comment by mmc46** [comment]
`statusLabel` does shows here https://neuprint-test.janelia.org/public/neuprintuserguide_012420.pdf but I don't have any other info on why it might be different to `status`. Maybe worth asking on the FLYEM Slack?

**Comment by jefferis** [comment]
Ok! So it is vague!

**Comment by romainFr** [comment]
I asked, and have been told that `statusLabel` is a more detailed version of  `status`. In `status`, a bunch of things (like `leaves` and `roughly traced`) are lumped together as `Traced`.

**Comment by jefferis** [comment]
@romainFr are we happy with:

> \item statusLabel similar to \code{status} but often a bit more specific

**Comment by romainFr** [comment]
yes!
