### ISSUE TITLE
break down queries that are too large

### ISSUE THREAD

**Issue by romainFr** [natverse/neuprintr#89]
Really large queries result in a timeout error from the server. It should be possible to break down those and rebuild the results. Either through a tryCatch or by setting thresholds on query sizes for various functions.

**Comment by schlegelp** [comment]
Batching queries is one way of mitigating time-outs but Stuart also found that the neoj4 planner appears to misbehave when using large lists of bodyIds. You can trick the planner into behaving by changing the query. See here:

https://github.com/connectome-neuprint/neuprint-python/issues/7

**Comment by romainFr** [comment]
Progress made in #98 #99 and #100 . Any other places we'd like to chunk ?

**Comment by jefferis** [comment]
Thanks @romainFr. I think that's good for now. See also 7921b21f67e40e59af971479058914089c4ba4c4 and 4c6b814d6ab56c983ca0c1bd2659d5a291859e71 for some points to bear in mind if we add chunking to any more functions.
